## Pandas
**Followed** : "Pandas tutorial: A Complete Pandas Tutorial" from Kaggle ([Link](https://www.kaggle.com/code/rajmehra03/a-complete-pandas-tutorial))
<br>
**Dataset** : "Pandas Practice Dataset" from Kaggle ([Link](https://www.kaggle.com/datasets/themrityunjaypathak/pandas-practice-dataset?resource=download))

**1. Importing dataset**

This dataset has 5 columns:<br>
1. Serial number (from 0 to 31)<br>
2. Duration of time in minutes
3. Date of recording of patient
4. Pulse of patient
5. Calories of patient

In [98]:
import numpy as np
import pandas as pd

**2. About the dataset**

In [99]:
df = pd.read_csv('data.csv')
df.head()

   Duration          Date  Pulse  Maxpulse  Calories
0        60  '2020/12/01'    110       130     409.1
1        60  '2020/12/02'    117       145     479.0
2        60  '2020/12/03'    103       135     340.0
3        45  '2020/12/04'    109       175     282.4
4        45  '2020/12/05'    117       148     406.0

In [100]:
df.tail()

    Duration          Date  Pulse  Maxpulse  Calories
27        60  '2020/12/27'     92       118     241.0
28        60  '2020/12/28'    103       132       NaN
29        60  '2020/12/29'    100       132     280.0
30        60  '2020/12/30'    102       129     380.3
31        60  '2020/12/31'     92       115     243.0

In [101]:
df.describe()

         Duration       Pulse    Maxpulse    Calories
count   32.000000   32.000000   32.000000   30.000000
mean    68.437500  103.500000  128.500000  304.680000
std     70.039591    7.832933   12.998759   66.003779
min     30.000000   90.000000  101.000000  195.100000
25%     60.000000  100.000000  120.000000  250.700000
50%     60.000000  102.500000  127.500000  291.200000
75%     60.000000  106.500000  132.250000  343.975000
max    450.000000  130.000000  175.000000  479.000000

In [102]:
df.shape

(32, 5)

In [103]:
df.columns

Index(['Duration', 'Date', 'Pulse', 'Maxpulse', 'Calories'], dtype='str')

In [104]:
df.index

RangeIndex(start=0, stop=32, step=1)

**3. Creating a dataframe**: A Pandas DataFrame is a two-dimensional, table-like, size-mutable data structure with labeled axes (rows and columns)
<br>
It can be heterogenous in datatypes, like an Excel sheet and makes data manipulation easier than when using NumPy arrays

In [105]:
df_empty = pd.DataFrame()
df_empty.head()

Empty DataFrame
Columns: []
Index: []

In [106]:
patient_record_dict = { "Name":['X','Y','Z'],
                       'Age' : [20,21,25],
                       'Roll' : [2,24,95]
}
print(patient_record_dict)
df_patient = pd.DataFrame(patient_record_dict)
df_patient.head()

{'Name': ['X', 'Y', 'Z'], 'Age': [20, 21, 25], 'Roll': [2, 24, 95]}

  Name  Age  Roll
0    X   20     2
1    Y   21    24
2    Z   25    95

**4. Treating Null values**

In [107]:
df.head()

   Duration          Date  Pulse  Maxpulse  Calories
0        60  '2020/12/01'    110       130     409.1
1        60  '2020/12/02'    117       145     479.0
2        60  '2020/12/03'    103       135     340.0
3        45  '2020/12/04'    109       175     282.4
4        45  '2020/12/05'    117       148     406.0

In [108]:
# counts the number of missing (NaN) values in each column
df.isnull().sum()

Duration    0
Date        1
Pulse       0
Maxpulse    0
Calories    2
dtype: int64

In [109]:
# Filling in the Nan Date columns with the most recent date(forward fill)
df['Date'] = pd.to_datetime(df['Date'], format='mixed')
df['Date'] = df['Date'].ffill()

In [110]:
# To force all dates into a stanrd YYYY-MM-DD format
df['Date'] = df['Date'].dt.strftime('%Y-%m-%d')

In [111]:
# Filling in the NaN calories with the mean
df['Calories'] = df['Calories'].fillna(df['Calories'].mean())

In [112]:
df.isnull().sum()

Duration    0
Date        0
Pulse       0
Maxpulse    0
Calories    0
dtype: int64

**5. Conditional filtering/slicing**

In [113]:
df.head()

   Duration        Date  Pulse  Maxpulse  Calories
0        60  2020-12-01    110       130     409.1
1        60  2020-12-02    117       145     479.0
2        60  2020-12-03    103       135     340.0
3        45  2020-12-04    109       175     282.4
4        45  2020-12-05    117       148     406.0

In [117]:
# Filtering for rows in which Pulse is above 100
df['Pulse'] = df['Pulse'].astype(int)
high_intensity = df[df['Pulse'] > 100]
print(high_intensity)

    Duration        Date  Pulse  Maxpulse  Calories
0         60  2020-12-01    110       130    409.10
1         60  2020-12-02    117       145    479.00
2         60  2020-12-03    103       135    340.00
3         45  2020-12-04    109       175    282.40
4         45  2020-12-05    117       148    406.00
5         60  2020-12-06    102       127    300.00
6         60  2020-12-07    110       136    374.00
7        450  2020-12-08    104       134    253.30
8         30  2020-12-09    109       133    195.10
10        60  2020-12-11    103       147    329.30
13        60  2020-12-13    106       128    345.30
14        60  2020-12-14    104       132    379.30
19        60  2020-12-19    103       123    323.00
21        60  2020-12-21    108       131    364.20
23        60  2020-12-23    130       101    300.00
24        45  2020-12-24    105       132    246.00
25        60  2020-12-25    102       126    334.50
28        60  2020-12-28    103       132    304.68
30        60  2020-12-30    102       129    380.30

In [ ]:
# Filtering for workouts that lasted over 30 mins and also burned more than 300 calories
Cal_30 = df[(df['Duration'] > 30) & (df['Calories'] > 300)]
print(Cal_30)

    Duration        Date  Pulse  Maxpulse  Calories
0         60  2020-12-01    110       130    409.10
1         60  2020-12-02    117       145    479.00
2         60  2020-12-03    103       135    340.00
4         45  2020-12-05    117       148    406.00
6         60  2020-12-07    110       136    374.00
10        60  2020-12-11    103       147    329.30
13        60  2020-12-13    106       128    345.30
14        60  2020-12-14    104       132    379.30
18        45  2020-12-18     90       112    304.68
19        60  2020-12-19    103       123    323.00
21        60  2020-12-21    108       131    364.20
25        60  2020-12-25    102       126    334.50
28        60  2020-12-28    103       132    304.68
30        60  2020-12-30    102       129    380.30

**6. Data Aggregration and grouping**

In [122]:
# Grouping by Duration to see average calories and pulse for different lengths
df.groupby('Duration') [['Calories','Maxpulse']].mean()

            Calories    Maxpulse
Duration
30        195.100000  133.000000
45        294.013333  135.166667
60        314.053333  126.416667
450       253.300000  134.000000

In [124]:
df.groupby('Date')[['Pulse','Maxpulse']].max()

            Pulse  Maxpulse
Date
2020-12-01    110       130
2020-12-02    117       145
2020-12-03    103       135
2020-12-04    109       175
2020-12-05    117       148
2020-12-06    102       127
2020-12-07    110       136
2020-12-08    104       134
2020-12-09    109       133
2020-12-10     98       124
2020-12-11    103       147
2020-12-12    100       120
2020-12-13    106       128
2020-12-14    104       132
2020-12-15     98       123
2020-12-16     98       120
2020-12-17    100       120
2020-12-18     90       112
2020-12-19    103       123
2020-12-20     97       125
2020-12-21    108       131
2020-12-23    130       101
2020-12-24    105       132
2020-12-25    102       126
2020-12-26    100       120
2020-12-27     92       118
2020-12-28    103       132
2020-12-29    100       132
2020-12-30    102       129
2020-12-31     92       115

**7. Creating new features/ Feature engineering**

In [129]:
df['Cal_per_minute'] = df['Calories']/df['Duration']
print(df['Cal_per_minute'])

0     6.818333
1     7.983333
2     5.666667
3     6.275556
4     9.022222
5     5.000000
6     6.233333
7     0.562889
8     6.503333
9     4.483333
10    5.488333
11    4.178333
12    4.178333
13    5.755000
14    6.321667
15    4.583333
16    3.586667
17    5.000000
18    6.770667
19    5.383333
20    5.400000
21    6.070000
22    6.266667
23    5.000000
24    5.466667
25    5.575000
26    4.166667
27    4.016667
28    5.078000
29    4.666667
30    6.338333
31    4.050000
Name: Cal_per_minute, dtype: float64

In [132]:
df['Pulse_Spike'] = df['Maxpulse'] - df['Pulse']
print(df['Pulse_Spike'])

0     20
1     28
2     32
3     66
4     31
5     25
6     26
7     30
8     24
9     26
10    44
11    20
12    20
13    22
14    28
15    25
16    22
17    20
18    22
19    20
20    28
21    23
22    19
23   -29
24    27
25    24
26    20
27    26
28    29
29    32
30    27
31    23
Name: Pulse_Spike, dtype: int64